"""Model-agnostic confidence parser from vision model text output.

Derives a numeric confidence score (0.0-1.0) from free-text model descriptions
when the underlying vision model does not natively return a confidence value.
Used as a fallback in normalize_model_result() and decide_escalation().

Pattern matching is data-driven: reason codes come from Xano at runtime.
New reason codes are automatically picked up — no hardcoded reason code list.
"""

from __future__ import annotations

from typing import Any

# Default supplemental patterns — used when Xano reason_codes don't have
# their own pattern lists attached. These cover the known high-severity cases.
DEFAULT_PATTERNS: dict[str, list[str]] = {
    "underage_concern": [
        "child", "children", "underage", "minor", "juvenile",
        "appears to be a child", "appears to be under", "young person",
        "person appears to be under 18", "under 18", "underage concern",
        "potentially a minor", "possibly a minor", "possibly underage",
        "may be a child", "may be a minor", "looks like a child",
        "age uncertain", "young appearing", "young-looking",
    ],
    "nudity_explicit": [
        "nudity", "nude", "naked", "explicit", "explicit sexual",
        "sexually explicit", "pornographic", "adult content",
        "explicit content", "genitals visible", "explicit nude",
    ],
    "sexual_content": [
        "sexual", "intimate area",
        "sex activity", "sexual act", "sexual context",
        "suggestive", "provocative", "erotic",
    ],
    "drug_use": [
        "drug", "drugs", "substance", "illegal substance",
        "controlled substance", "drug use", "using drugs",
        "paraphernalia", "bong", "pipe", "needle", "white powder",
        "white powder visible", "lines on surface", "snort",
    ],
    "money_request": [
        "solicits money", "money request", "payment",
        "payment request", "cash app", "venmo", "paypal",
        "gift card request", "wire transfer", "sends money",
        "asking for money", "financial request",
    ],
    "hate_symbols": [
        "hate symbol", "hate imagery", "extremist", "white power",
        "nazi", "supremacist", "hate group", "swastika",
        "klan", "racist symbol", "extremist content",
    ],
    "violence_credible": [
        "violence", "violent", "weapon", "gun", "knife",
        "blood", "injury", "assault", "attack", "harm",
        "credible threat", "threatening", "domestic violence",
        "fighting", "brutality",
    ],
    "self_harm": [
        "self harm", "self-harm", "suicide", "suicidal",
        "cutting", "self injury", "overdose", "intentional overdose",
    ],
    "ai_generated": [
        "ai generated", "artificial intelligence", "ai-generated",
        "synthetic", "generated by ai", "created by ai",
        "not a real photo", "not a real person", "deepfake",
        "digitally created", "computer generated",
    ],
    "celebrity_or_stock_photo": [
        "celebrity", "famous person", "public figure",
        "stock photo", "stock imagery", "model release",
        "professional photo", "clearly a stock photo",
    ],
    "low_quality": [
        "low quality", "blurry", "out of focus", "grainy",
        "pixelated", "poor quality", "low-resolution",
        "motion blur", "dark image", "poor lighting",
    ],
    "unclear_subject": [
        "unclear", "cannot determine", "cannot tell", "unclear subject",
        "no clear subject", "multiple subjects", "crowd",
        "no person visible", "subject not identifiable",
        "cannot identify", "indistinct", "obscured",
    ],
    "object_or_landscape_only": [
        "object or landscape", "no person", "only object",
        "only landscape", "no human", "scenery", "place",
        "building", "outdoor scene", "indoor scene", "sky",
        "nature", "animal", "food", "product photo",
    ],
}

# Language-signal words that indicate model confidence ( hedging vs. definitive )
_STRONG_POSITIVE = {
    "clearly", "definitely", "certainly", "unequivocally",
    "obviously", "plainly", "visibly", "distinctly",
    "no concern", "no issue", "no problem", "no safety",
    "no inappropriate", "appropriate", "well posed",
    "good quality", "clearly visible", "clearly adult",
    "clearly a person", "single clearly visible",
}

_STRONG_NEGATIVE = {
    "explicit", "pornographic", "undeniable", "confirmed",
    "clearly inappropriate", "clearly illegal",
    "obvious minor", "obvious child", "definite underage",
}

_HEDGING = {
    "possibly", "maybe", "might be", "may be", "could be",
    "uncertain", "unclear", "unidentifiable", "cannot determine",
    "hard to tell", "difficult to", "may appear",
    "questionable", "indeterminate", "ambiguous", "ambiguously",
}


def confidence_from_text(
    text: str,
    reason_codes: list[dict[str, Any]],
    patterns: dict[str, list[str]] | None = None,
) -> tuple[float, str | None]:
    """Derive confidence score and matched reason code from model description text.

    Args:
        text: Raw model description / verdict text (lowercase-insensitive match).
        reason_codes: List of reason code dicts from Xano.
            Expected fields per item: code, label, severity, auto_reject_threshold.
        patterns: Optional override patterns dict.
            If None, DEFAULT_PATTERNS is used.

    Returns:
        (confidence_score 0.0-1.0, matched_reason_code_or_None)

    Confidence logic:
        1. Match text against patterns → use matched code's auto_reject_threshold
        2. No pattern match, but strong positive language → 0.88
        3. No pattern match, but hedging language → 0.50
        4. No match, no hedge, has content → 0.60
        5. Empty or garbage text → 0.0
    """
    if not text or not isinstance(text, str):
        return 0.0, None

    text_lower = text.lower()
    patterns = patterns or DEFAULT_PATTERNS

    # --- Empty / garbage check early ---
    stripped = text_lower.strip()
    if not stripped:
        return 0.0, None
    # Garbage = fewer than 5 alpha characters (pure symbol/number noise)
    alpha_chars = [c for c in stripped if c.isalpha()]
    if len(alpha_chars) < 5:
        return 0.0, None

    # Build code→threshold lookup from reason_codes
    code_threshold: dict[str, float] = {}
    code_severity: dict[str, str] = {}
    for rc in reason_codes:
        code = rc.get("code")
        if not code:
            continue
        code_threshold[code] = float(rc.get("auto_reject_threshold") or 0.0)
        code_severity[code] = rc.get("severity", "low")

    # Severity order for tie-breaking
    severity_rank = {"high": 0, "medium": 1, "low": 2}

    # Find best pattern match
    best_match_code: str | None = None
    best_match_severity_rank = 99
    best_match_confidence = 0.0

    for code, keywords in patterns.items():
        # Only match against codes that exist in reason_codes
        if code not in code_threshold:
            continue
        for kw in keywords:
            if kw in text_lower:
                sev_rank = severity_rank.get(code_severity.get(code, "low"), 99)
                # Use threshold if set; zero-threshold codes get 0.90 default
                candidate_confidence = code_threshold[code]
                if candidate_confidence <= 0:
                    candidate_confidence = 0.90
                if sev_rank < best_match_severity_rank or candidate_confidence > best_match_confidence:
                    best_match_code = code
                    best_match_severity_rank = sev_rank
                    best_match_confidence = candidate_confidence
                break  # First keyword hit for this code is enough

    if best_match_code is not None:
        return round(best_match_confidence, 2), best_match_code

    # No pattern match — fall back to language analysis
    if any(w in text_lower for w in _STRONG_POSITIVE):
        return 0.88, None
    if any(w in text_lower for w in _STRONG_NEGATIVE):
        return 0.90, None
    if any(w in text_lower for w in _HEDGING):
        return 0.50, None

    # Has content but no strong signal
    if len(stripped) > 20:
        return 0.60, None

    return 0.0, None


def expand_patterns_from_reason_codes(
    reason_codes: list[dict[str, Any]],
    patterns: dict[str, list[str]] | None = None,
) -> dict[str, list[str]]:
    """Build the full patterns dict by combining DEFAULT_PATTERNS with
    any custom pattern lists attached to reason_codes from Xano.

    Reason codes from Xano may include a 'patterns' field (list[str]).
    If present, it supplements (or overrides) the default keywords.
    """
    result = dict(patterns or DEFAULT_PATTERNS)

    for rc in reason_codes:
        code = rc.get("code")
        if not code:
            continue
        custom = rc.get("patterns")
        if custom:
            existing = set(result.get(code, []))
            result[code] = list(existing | set(custom))

    return result
