// GENERATED by issue-458-motion-composer-v1/emit-registration-ts.mjs — do not edit by hand.
// Review-only Motion Forge packs authored by the motion composer; hash-pinned to exact bytes.
// Strike windows are clip seconds around the reach-solved contact frame; vertices are
// indexed tip vertices of the striking region at that frame (Breachling_Mesh).

export interface ComposerStrike { readonly start: number; readonly end: number; readonly vertices: readonly number[]; readonly phase: string; readonly revision: string; }
export interface ComposerMobPack {
  readonly variant: "base" | "stalker" | "oathbound" | "ravager";
  readonly url: string; readonly bytes: number; readonly sha256: string; readonly runtimeSourceSha256: string;
  readonly runtimeScale: number; readonly actions: readonly string[]; readonly neutralHolds: readonly string[];
  readonly revision: string; readonly strikes: Readonly<Record<string, ComposerStrike>>;
  readonly spit: { readonly releaseSeconds: number; readonly endSeconds: number } | null;
  readonly toeBones: readonly string[]; // toe-rig bones appended to the source skeleton (empty for legacy rigs)
}

export const COMPOSER_MOB_PACKS: Readonly<Partial<Record<ComposerMobPack["variant"], ComposerMobPack>>> = Object.freeze({
  base: Object.freeze({
    variant: "base", url: "/assets/weapon-lab/mobs/breachling-base-composer-v94.glb", bytes: 12484648, sha256: "54358045f86ffe411a6db6bea43af63a7746ac7a691fc1ddbfd2498e2cbbfcb3",
    runtimeSourceSha256: "00921227fb9a2c3049363c1a8bda35bb8acf20a73811e3ad86c6256bd91b0cc7", runtimeScale: 1.7714769640700978,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v94",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [15549,15548,15547], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v94" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [1258,1259,778], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v94" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [15358,15205,15206], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v94" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [35354,35353,35350], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v94" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe4L","front_toe1R","front_toe2R","front_toe3R","front_toe4R","rear_toe1L","rear_toe2L","rear_toe3L","rear_toe1R","rear_toe2R","rear_toe3R"],
  }),
  stalker: Object.freeze({
    variant: "stalker", url: "/assets/weapon-lab/mobs/breachling-stalker-composer-v23.glb", bytes: 11418068, sha256: "f349311f5548890f311b1ee3f80d65cc86411a18db94d1b73eeadf5e1f49f57c",
    runtimeSourceSha256: "1f61df8716b60dd376959dbff1295c708f770d3601cf9781263d1996f808a641", runtimeScale: 2.253428958684859,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v23",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [24003,24001,24002], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v23" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [400,399,402], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v23" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [16936,16937,16879], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v23" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [13640,13639,13641], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v23" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe4L","front_toe1R","front_toe2R","front_toe3R","front_toe4R","rear_toe1L","rear_toe2L","rear_toe3L","rear_toe1R","rear_toe2R","rear_toe3R"],
  }),
  oathbound: Object.freeze({
    variant: "oathbound", url: "/assets/weapon-lab/mobs/breachling-oathbound-composer-v13.glb", bytes: 11861332, sha256: "b22cc5503fd7950f85cc09716ce203c9b5c183fec5facd72b7734b85f9b3b0ca",
    runtimeSourceSha256: "077e130cd8a9fa0a755aed1c1efe1f268f8ef08470762adead1b7bf0e2948939", runtimeScale: 2.05656927752596,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v13",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [18476,18478,18477], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v13" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [1,5,2], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v13" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [11864,11862,11867], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v13" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [35169,35168,35261], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v13" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe4L","front_toe1R","front_toe2R","front_toe3R","front_toe4R","rear_toe1L","rear_toe2L","rear_toe3L","rear_toe1R","rear_toe2R","rear_toe3R"],
  }),
  ravager: Object.freeze({
    variant: "ravager", url: "/assets/weapon-lab/mobs/breachling-ravager-composer-v17.glb", bytes: 10978388, sha256: "f65b44d91e4dff4d041336572a97c58e4558b9e59f0831347519e7fe711a2866",
    runtimeSourceSha256: "cd8fa4f5daf6f789e80322fad2ed7df15cb7b6dcea0dec19c0d869478f08e22c", runtimeScale: 1.6278343683021053,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v17",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [1890,1886,1888], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v17" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [411,410,409], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v17" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [1053,1054,1055], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v17" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [35131,35130,35129], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v17" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe4L","front_toe1R","front_toe2R","front_toe3R","front_toe4R","rear_toe1L","rear_toe2L","rear_toe3L","rear_toe1R","rear_toe2R","rear_toe3R"],
  }),
});
