// GENERATED by issue-458-motion-composer-v1/emit-registration-ts.mjs — do not edit by hand.
// Review-only Motion Forge packs authored by the motion composer; hash-pinned to exact bytes.
// Strike windows are clip seconds around the reach-solved contact frame; vertices are
// indexed tip vertices of the striking region at that frame (Breachling_Mesh).

export interface ComposerStrike { readonly start: number; readonly end: number; readonly vertices: readonly number[]; readonly phase: string; readonly revision: string; }
export interface ComposerMobPack {
  readonly variant: "base" | "stalker" | "oathbound" | "ravager";
  readonly url: string; readonly bytes: number; readonly sha256: string; readonly runtimeSourceSha256: string;
  readonly runtimeScale: number; readonly actions: readonly string[]; readonly neutralHolds: readonly string[];
  readonly revision: string; readonly strikes: Readonly<Record<string, ComposerStrike>>;
  readonly spit: { readonly releaseSeconds: number; readonly endSeconds: number } | null;
  readonly toeBones: readonly string[]; // toe-rig bones appended to the source skeleton (empty for legacy rigs)
  readonly body: "legacy" | "fourview"; // legacy single-view Tripo body or the four-view remodel (issue 458, 2026-09-05 owner decision)
}

// Legacy single-view bodies (dungeon runtime lineage).
export const COMPOSER_MOB_PACKS: Readonly<Partial<Record<ComposerMobPack["variant"], ComposerMobPack>>> = Object.freeze({
  base: Object.freeze({
    variant: "base", url: "/assets/weapon-lab/mobs/breachling-base-composer-v95.glb", bytes: 12484648, sha256: "0761165e41dbd4a6e3a38462f8a3cd69a6bc9b5c75e68dd8236f785ff9d00791",
    runtimeSourceSha256: "00921227fb9a2c3049363c1a8bda35bb8acf20a73811e3ad86c6256bd91b0cc7", runtimeScale: 1.7714769640700978,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v95",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [15549,15548,15547], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v95" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [1258,1259,778], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v95" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [15358,15205,15206], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v95" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [35354,35353,35350], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v95" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe4L","front_toe1R","front_toe2R","front_toe3R","front_toe4R","rear_toe1L","rear_toe2L","rear_toe3L","rear_toe1R","rear_toe2R","rear_toe3R"],
    body: "legacy",
  }),
  ravager: Object.freeze({
    variant: "ravager", url: "/assets/weapon-lab/mobs/breachling-ravager-composer-v20.glb", bytes: 10981168, sha256: "4e75cf5eb40d70e5c88424c29585de2c298ecc1eb2c3be8388c21f0e8845c385",
    runtimeSourceSha256: "cd8fa4f5daf6f789e80322fad2ed7df15cb7b6dcea0dec19c0d869478f08e22c", runtimeScale: 1.6278343683021053,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v20",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [1890,1886,1888], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v20" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [411,410,409], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v20" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [1053,1054,1055], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v20" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [35131,35130,35129], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v20" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe4L","front_toe1R","front_toe2R","front_toe3R","front_toe4R","rear_toe1L","rear_toe2L","rear_toe3L","rear_toe1R","rear_toe2R","rear_toe3R"],
    body: "legacy",
  }),
  stalker: Object.freeze({
    variant: "stalker", url: "/assets/weapon-lab/mobs/breachling-stalker-composer-v24.glb", bytes: 11418068, sha256: "e4e0e56d335f1cb013a51f5412396995fc19c0711c6b901e5536c6d0a4288427",
    runtimeSourceSha256: "1f61df8716b60dd376959dbff1295c708f770d3601cf9781263d1996f808a641", runtimeScale: 2.253428958684859,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v24",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [24003,24001,24002], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v24" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [400,399,402], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v24" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [16936,16937,16879], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v24" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [13640,13639,13641], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v24" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe4L","front_toe1R","front_toe2R","front_toe3R","front_toe4R","rear_toe1L","rear_toe2L","rear_toe3L","rear_toe1R","rear_toe2R","rear_toe3R"],
    body: "legacy",
  }),
  oathbound: Object.freeze({
    variant: "oathbound", url: "/assets/weapon-lab/mobs/breachling-oathbound-composer-v14.glb", bytes: 11861332, sha256: "36100ba5dd4dccac0ce80296f0eff1ba41dd9c9233ca3043c8472864c2f55015",
    runtimeSourceSha256: "077e130cd8a9fa0a755aed1c1efe1f268f8ef08470762adead1b7bf0e2948939", runtimeScale: 2.05656927752596,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v14",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [18476,18478,18477], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v14" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [1,5,2], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v14" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [11864,11862,11867], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v14" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [35169,35168,35261], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v14" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe4L","front_toe1R","front_toe2R","front_toe3R","front_toe4R","rear_toe1L","rear_toe2L","rear_toe3L","rear_toe1R","rear_toe2R","rear_toe3R"],
    body: "legacy",
  }),
});

// Four-view remodel bodies: Tripo multi-view meshes, Tripo auto-rig converted to the canonical skeleton. Review-only; not dungeon runtime.
export const COMPOSER_MOB_PACKS_FOURVIEW: Readonly<Partial<Record<ComposerMobPack["variant"], ComposerMobPack>>> = Object.freeze({
  ravager: Object.freeze({
    variant: "ravager", url: "/assets/weapon-lab/mobs/breachling-ravager-fourview-composer-v4.glb", bytes: 16843992, sha256: "7d820c38022469d1c03910d63e4562322ec615bc17462c1ffab2e4c8f8ad5971",
    runtimeSourceSha256: "cd8fa4f5daf6f789e80322fad2ed7df15cb7b6dcea0dec19c0d869478f08e22c", runtimeScale: 1.5839816537015536,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v4",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [16198,16203,16207], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v4" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [8748,8652,8669], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v4" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [8748,8652,8959], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v4" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [28214,28219,28216], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v4" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe1R","front_toe2R","front_toe3R","rear_toe1L","rear_toe1R","rear_toe2R","rear_toe3R"],
    body: "fourview",
  }),
  stalker: Object.freeze({
    variant: "stalker", url: "/assets/weapon-lab/mobs/breachling-stalker-fourview-composer-v5.glb", bytes: 15559440, sha256: "c98664174c1c3da6bf9d804234f0f5d9c133663beaecbcb67a856706bc00356d",
    runtimeSourceSha256: "1f61df8716b60dd376959dbff1295c708f770d3601cf9781263d1996f808a641", runtimeScale: 1.1994050642631422,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v5",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [20686,20682,20687], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v5" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [14382,14209,14193], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v5" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [14286,14196,14415], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v5" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [28054,28051,28047], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v5" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["rear_toe1L","rear_toe1R"],
    body: "fourview",
  }),
  base: Object.freeze({
    variant: "base", url: "/assets/weapon-lab/mobs/breachling-base-fourview-composer-v8.glb", bytes: 16111960, sha256: "625055eef3c3a8cd755f343aedfd70e0ecb4310a953ad60b39430be455c2b9c0",
    runtimeSourceSha256: "00921227fb9a2c3049363c1a8bda35bb8acf20a73811e3ad86c6256bd91b0cc7", runtimeScale: 1.306614490956487,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-v8",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [20325,20292,19681], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-v8" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [11669,11591,11560], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-v8" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [16424,16337,16143], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-v8" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [28815,28823,28817], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-v8" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe1R","front_toe2R","front_toe3R"],
    body: "fourview",
  }),
  oathbound: Object.freeze({
    variant: "oathbound", url: "/assets/weapon-lab/mobs/breachling-oathbound-fourview-composer-q4.glb", bytes: 15780880, sha256: "19e755955a10ff5ed870151288b4038a91af940d67071e7f42518e68818fc8c1",
    runtimeSourceSha256: "077e130cd8a9fa0a755aed1c1efe1f268f8ef08470762adead1b7bf0e2948939", runtimeScale: 1.497870060025395,
    actions: ["Walk","Run","BiteAttack","ClawAttack","LungeAttack","TailWhip","SpitAttack","RecieveHit","RecieveHitHeavy","RecieveHitLeft","RecieveHitRight","RecieveHitBack","Death"], neutralHolds: ["Idle","CombatIdle"], revision: "composer-q4",
    strikes: Object.freeze({
      BiteAttack: { start: 0.4233, end: 0.5833, vertices: [16285,16328,16322], phase: "BiteAttack contact 0.4833s via head+jaw", revision: "composer-q4" },
      ClawAttack: { start: 0.3233, end: 0.4833, vertices: [10754,10954,10323], phase: "ClawAttack contact 0.3833s via front_handR", revision: "composer-q4" },
      LungeAttack: { start: 0.39, end: 0.55, vertices: [10323,10856,10754], phase: "LungeAttack contact 0.45s via front_handL+front_handR", revision: "composer-q4" },
      TailWhip: { start: 0.7567, end: 0.9167, vertices: [27789,27752,27826], phase: "TailWhip contact 0.8167s via tail003+tail004+tail005", revision: "composer-q4" },
    }),
    spit: { releaseSeconds: 0.45, endSeconds: 1.2 },
    toeBones: ["front_toe1L","front_toe2L","front_toe3L","front_toe4L","front_toe1R","front_toe2R","front_toe3R","front_toe4R","rear_toe1L","rear_toe2L","rear_toe3L","rear_toe1R","rear_toe2R","rear_toe3R"],
    body: "fourview",
  }),
});
